# This file is part of MongoTUI.

# MongoTUI is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# MongoTUI is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with MongoTUI.  If not, see <http://www.gnu.org/licenses/>.

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps: 
- bash: |
  'env'
- task: GoTool@0
  inputs:
    version: '1.14.7'
- task: Go@0
  displayName: 'Get packages'
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  displayName: 'Build app'
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop
- task: GitHubRelease@1
  condition: ne(variables.releaseTag, '')
  inputs:
    gitHubConnection: 'github.com_renkman'
    repositoryName: 'renkman/mongotui'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: $(releaseTag)
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
    assets: |
      $(Build.ArtifactStagingDirectory)/mongotui
