name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build MongoTUI
      run: go build -v ./...

    - name: Run mongo docker image for tests
      run: docker run -d -p 127.0.0.1:27017:27017 mongo

    - name: Create gpg key
      run: | 
        cat >gen-key-script <<EOF
          Key-Type: 1
          Key-Length: 2048
          Subkey-Type: 1
          Subkey-Length: 2048
          Name-Real: Keyring Test
          Name-Email: keyring@test.invalid
          Expire-Date: 0
          Passphrase: foobar123
          %commit
        EOF
        gpg --batch --gen-key gen-key-script
        echo "Generated key"
        gpg --list-keys | awk 'NR==4 { print $1 }'            

    - name:  Init pass
      run: |
        key=$(gpg --list-keys | awk 'NR==4 { print $1 }')
          echo "Key in var"
          echo $key

          echo "Init pass"
          pass init $key

    - name: Test MongoTUI
      run: go test -v ./...
